version: '3'
services:
  mongo:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=username
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=notification_db
    ports:
      - 27018:27017
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - ./:/etc/kafka
